# Installed required libraries

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt

print('Libraries loaded.')

Libraries loaded.


# Loading dataset

In [2]:
file = open('Data/iris.txt', 'r')

data = file.read().split()

file.close()

print('Data loaded and the opened file stream has closed.')

Data loaded and the opened file stream has closed.


In [3]:
data

['5.9,3,4.2,1.5,"Iris-versicolor"',
 '6.9,3.1,4.9,1.5,"Iris-versicolor"',
 '6.6,2.9,4.6,1.3,"Iris-versicolor"',
 '4.6,3.2,1.4,0.2,"Iris-setosa"',
 '6,2.2,4,1,"Iris-versicolor"',
 '4.7,3.2,1.3,0.2,"Iris-setosa"',
 '6.5,3,5.8,2.2,"Iris-virginica"',
 '5.8,2.7,5.1,1.9,"Iris-virginica"',
 '6.7,3.1,5.6,2.4,"Iris-virginica"',
 '6.7,2.5,5.8,1.8,"Iris-virginica"',
 '5.1,3.7,1.5,0.4,"Iris-setosa"',
 '5.1,3.8,1.5,0.3,"Iris-setosa"',
 '5.7,3,4.2,1.2,"Iris-versicolor"',
 '6.1,3,4.9,1.8,"Iris-virginica"',
 '4.9,3.1,1.5,0.1,"Iris-setosa"',
 '5,3.4,1.6,0.4,"Iris-setosa"',
 '5,3.4,1.5,0.2,"Iris-setosa"',
 '5.7,2.8,4.1,1.3,"Iris-versicolor"',
 '5,3.3,1.4,0.2,"Iris-setosa"',
 '7.2,3.2,6,1.8,"Iris-virginica"',
 '5.9,3,5.1,1.8,"Iris-virginica"',
 '6.5,3,5.2,2,"Iris-virginica"',
 '5.7,4.4,1.5,0.4,"Iris-setosa"',
 '5.5,2.5,4,1.3,"Iris-versicolor"',
 '4.9,2.5,4.5,1.7,"Iris-virginica"',
 '5,3.5,1.6,0.6,"Iris-setosa"',
 '5.5,2.3,4,1.3,"Iris-versicolor"',
 '4.6,3.1,1.5,0.2,"Iris-setosa"',
 '7.2,3,5.8,1.6,"Iris-v

In [4]:
prepared_data = []

classes = []

vectorized_float = np.vectorize(float)

for line in data:
    
    l = line.split(',')
    
    prepared_data.append(vectorized_float(l[0: 4]))
    
    classes.append(l[-1][1:-1])
###   
    
prepared_data   

[array([5.9, 3. , 4.2, 1.5]),
 array([6.9, 3.1, 4.9, 1.5]),
 array([6.6, 2.9, 4.6, 1.3]),
 array([4.6, 3.2, 1.4, 0.2]),
 array([6. , 2.2, 4. , 1. ]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([6.5, 3. , 5.8, 2.2]),
 array([5.8, 2.7, 5.1, 1.9]),
 array([6.7, 3.1, 5.6, 2.4]),
 array([6.7, 2.5, 5.8, 1.8]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.7, 3. , 4.2, 1.2]),
 array([6.1, 3. , 4.9, 1.8]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5. , 3.4, 1.5, 0.2]),
 array([5.7, 2.8, 4.1, 1.3]),
 array([5. , 3.3, 1.4, 0.2]),
 array([7.2, 3.2, 6. , 1.8]),
 array([5.9, 3. , 5.1, 1.8]),
 array([6.5, 3. , 5.2, 2. ]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.5, 2.5, 4. , 1.3]),
 array([4.9, 2.5, 4.5, 1.7]),
 array([5. , 3.5, 1.6, 0.6]),
 array([5.5, 2.3, 4. , 1.3]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([7.2, 3. , 5.8, 1.6]),
 array([6.8, 3.2, 5.9, 2.3]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5. , 3.2, 1.2, 0.2]),
 array([5.7, 2.5, 5. , 2. ]),
 array([5.

# Creating a dateframe

In [5]:
dataset = pd.DataFrame(prepared_data, 
                       columns= ['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

dataset['class'] = classes

dataset.head()

sepal_length  sepal_width  petal_length  petal_width            class
0           5.9          3.0           4.2          1.5  Iris-versicolor
1           6.9          3.1           4.9          1.5  Iris-versicolor
2           6.6          2.9           4.6          1.3  Iris-versicolor
3           4.6          3.2           1.4          0.2      Iris-setosa
4           6.0          2.2           4.0          1.0  Iris-versicolor

In [6]:
type(dataset)

pandas.core.frame.DataFrame

In [7]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# The best way for reading files into dataframes

In [8]:
df_iris = pd.read_csv('Data/iris.txt', sep= ',', header= None) 
df_iris.head()

0    1    2    3                4
0  5.9  3.0  4.2  1.5  Iris-versicolor
1  6.9  3.1  4.9  1.5  Iris-versicolor
2  6.6  2.9  4.6  1.3  Iris-versicolor
3  4.6  3.2  1.4  0.2      Iris-setosa
4  6.0  2.2  4.0  1.0  Iris-versicolor

In [9]:
df_iris.dtypes

0    float64
1    float64
2    float64
3    float64
4     object
dtype: object

# Preprocessing

In [10]:
df_iris.columns= ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'iris_name']

df_iris.head()

sepal_length  sepal_width  petal_length  petal_width        iris_name
0           5.9          3.0           4.2          1.5  Iris-versicolor
1           6.9          3.1           4.9          1.5  Iris-versicolor
2           6.6          2.9           4.6          1.3  Iris-versicolor
3           4.6          3.2           1.4          0.2      Iris-setosa
4           6.0          2.2           4.0          1.0  Iris-versicolor

In [11]:
encoder = LabelEncoder()

classes = encoder.fit_transform(df_iris['iris_name'])

df_iris['class'] = classes

df_iris

sepal_length  sepal_width  petal_length  petal_width        iris_name  \
0             5.9          3.0           4.2          1.5  Iris-versicolor   
1             6.9          3.1           4.9          1.5  Iris-versicolor   
2             6.6          2.9           4.6          1.3  Iris-versicolor   
3             4.6          3.2           1.4          0.2      Iris-setosa   
4             6.0          2.2           4.0          1.0  Iris-versicolor   
..            ...          ...           ...          ...              ...   
145           5.4          3.4           1.7          0.2      Iris-setosa   
146           5.5          2.6           4.4          1.2  Iris-versicolor   
147           6.7          3.0           5.2          2.3   Iris-virginica   
148           7.7          3.8           6.7          2.2   Iris-virginica   
149           5.1          3.4           1.5          0.2      Iris-setosa   

     class  
0        1  
1        1  
2        1  
3        0  
4        1  
..     ...  
145      0  
146      1  
147      2  
148      2  
149      0  

[150 rows x 6 columns]

In [12]:
dataset = df_iris.drop('iris_name', axis= 1)

dataset.head()

sepal_length  sepal_width  petal_length  petal_width  class
0           5.9          3.0           4.2          1.5      1
1           6.9          3.1           4.9          1.5      1
2           6.6          2.9           4.6          1.3      1
3           4.6          3.2           1.4          0.2      0
4           6.0          2.2           4.0          1.0      1

# Exploration

In [13]:
dataset.groupby(['class']).mean()

sepal_length  sepal_width  petal_length  petal_width
class                                                      
0             5.006        3.418         1.464        0.244
1             5.936        2.770         4.260        1.326
2             6.588        2.974         5.552        2.026

In [14]:
dataset.loc[0]

sepal_length    5.9
sepal_width     3.0
petal_length    4.2
petal_width     1.5
class           1.0
Name: 0, dtype: float64

In [15]:
dataset.loc[1]

sepal_length    6.9
sepal_width     3.1
petal_length    4.9
petal_width     1.5
class           1.0
Name: 1, dtype: float64

In [16]:
np.dot(dataset.loc[0], dataset.loc[1])

73.84